# Runs all tests and creates a coverage report
name: Coverage

on:  # Runs on all push events to master branch and any push related to a pull request
  push:
    branches:
      - master
  pull_request:

env:
  UV_COMPILE_BYTECODE: 1

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
        python-version: "3.13"

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          activate-environment: true
          cache-dependency-glob: '**/pyproject.toml'

      # The uv pip should make & use an env from the Python install of the previous step
      - name: Install package
        run: uv pip install '.[test]'

      - name: Run all tests
        run: python -m pytest --cov-report xml --cov-report term-missing --cov=cpymad_lhc

      - name: Show Coverage Report to PR
        uses: orgoro/coverage@v3.2
        if: ${{ success() }} && github.event_name == 'pull_request' # only if tests were successful, and a PR
        with:
          thresholdAll: 0.8  # we want at least 80% coverage for the package, fail if not
          thresholdNew: 0.6  # we want at least 80% coverage for the new code, fail if not
          thresholdModified: 0.6  # we want at least 60% coverage for the modified code, fail if not
          coverageFile: coverage.xml  # default when using '--cov-report xml' option above
          token: ${{ secrets.GITHUB_TOKEN }}